# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
image: node:16-alpine

definitions:
  caches:
    alpine-pkg: /var/cache/apk
    npm: ~/.npm

pipelines:
  default:
    - step:
        name: Main
        caches:
          - alpine-pkg
          - node
          - npm
        script:
          - apk update --quiet && apk upgrade --quiet
          - apk add --quiet --virtual node_installations build-base python3 py3-pip
          - npm -g i npm@latest && npm i --loglevel warn
          - npm audit fix || true
          - apk add --quiet --virtual os_installations tzdata
          - cp /usr/share/zoneinfo/Europe/Stockholm /etc/localtime && echo "Europe/Stockholm" > /etc/timezone
          - npm run build
          - npm run test:coverage
        artifacts:
          - 'node_modules/**'
          - '/var/cache/apk/**'
